apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: server
        image: harbor.c0.kube8.ga/boutique/frontend:96ac6093d28fa6c70b75dceacf310132c72f13b8
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-liveness-probe"
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice.boutique-production.global:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice.boutique-production.global:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice.boutique-production.global:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice.boutique-production.global:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice.boutique-production.global:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice.boutique-production.global:5050"
        - name: AD_SERVICE_ADDR
          value: "adservice.boutique-production.global:9555"
        - name: ENV_PLATFORM
          value: "azure"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 400m
            memory: 128Mi
